FROM python:3.9-slim-bullseye

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /usr/src/app
RUN chmod +x pepper.py

EXPOSE 80

CMD ["python"] ["pepper.py"]